export const SET_QUERY = "SET_QUERY";
export const START_FETCHING_MOVIES = "START_FETCHING_MOVIES";
export const SUCCESS_FETCHING_MOVIES = "SUCCESS_FETCHING_MOVIES";
export const FAILT_FETCHING_MOVIES = "FAIL_FETCHING_MOVIES";
